name: opicare
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.4.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  #conventional_changelog: ^2.0.0
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  git_hooks: ^1.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/

