name: opicare
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
